#!/usr/bin/env python3
"""
LinkedIn job search and auto-apply.
Supports Easy Apply (in-modal) and external ATS applications (Workday, Greenhouse, etc.).
Uses Claude AI for job scoring, cover letters, screening questions, and application notes.
"""

import logging

from jobapply import stats
from jobapply.accounts import (
    _attempt_account_creation,
    _attempt_ats_login,
    _extract_code_from_email_body,
    _fetch_verification_code_from_gmail,
    _fill_registration_form,
    _generate_ats_password,
    _get_domain,
    _handle_registration_verification,
    _load_ats_accounts,
    _save_ats_account,
)
from jobapply.ai import _AI_AVAILABLE, _get_ai_client
from jobapply.applog import (
    already_applied,
    load_log,
    save_log,
    save_search_log,
)
from jobapply.browser import (
    _STEALTH,
    _USER_AGENTS,
    _dismiss_linkedin_overlays,
    _ensure_logged_in,
    _human_delay,
    _inject_session_cookies_if_needed,
    _load_credentials,
    _login_linkedin,
    _playwright_context,
    _resolve_proxy,
    _save_credentials,
    _save_session,
    _stealth_playwright,
)
from jobapply.cli import (
    PROFILE_SYNC_INTERVAL_DAYS,
    _apply_synced_profile,
    _maybe_sync_profile,
    _run_setup,
    _sync_linkedin_profile,
    main,
)
from jobapply.config import (
    ATS_ACCOUNTS_FILE,
    CDP_URL,
    COVER_LETTER_DIR,
    CREDENTIALS_FILE,
    DATA_DIR,
    DEBUG_DIR,
    DEEP_APPLY_QUEUE_FILE,
    LOG_FILE,
    SEARCH_LOG_FILE,
    SESSION_FILE,
)
from jobapply.content import (
    _basic_cover_letter,
    _basic_notes,
    _ensure_cover_letter_docx,
    _save_cover_letter_docx,
    ai_build_notes,
    ai_generate_cover_letter,
    ai_score_job,
    score_job,
)
from jobapply.easy_apply import (
    _dismiss_save_dialog,
    _get_modal_text,
    _navigate_form,
    submit_easy_apply,
)
from jobapply.external import (
    _MAX_EXTERNAL_STEPS,
    _ai_find_navigation_button,
    _answer_external_screening_questions,
    _fill_custom_dropdown,
    _find_file_upload_inputs,
    _find_navigation_button,
    _get_custom_dropdown_options,
    _handle_file_uploads,
    _navigate_external_form,
    submit_external_apply,
)
from jobapply.forms import (
    _FORM_FILL_SYSTEM,
    _FORM_FILL_TEXTAREA_SYSTEM,
    _ai_answer_question,
    _answer_radio_buttons,
    _answer_screening_questions,
    _answer_select_dropdowns,
    _answer_textareas,
    _best_option_match,
    _build_form_prompt,
    _check_mandatory_checkboxes,
    _clamp_to_maxlength,
    _contact_value_for_label,
    _determine_radio_answer,
    _dismiss_all_typeaheads,
    _dismiss_typeahead,
    _dump_form_debug,
    _fill_empty_required_fields,
    _fill_input_field,
    _get_field_label,
    _get_form_container,
    _get_validation_errors,
    _match_screening_answer,
    _safe_click,
)
from jobapply.outreach import (
    _ai_draft_hiring_message,
    _extract_hiring_manager,
    _message_hiring_manager_after_apply,
    _send_hiring_manager_message,
)
from jobapply.pages import (
    _GUEST_SELECTORS,
    _PAGE_CLASSIFIER_SYSTEM,
    _RESUME_UPLOAD_BYPASS_SELECTORS,
    _2captcha_solve,
    _capsolver_solve,
    _classify_page,
    _detect_captcha,
    _detect_login_page,
    _detect_success_or_confirmation,
    _extract_page_snapshot,
    _inject_captcha_token,
    _resolve_login_wall,
    _solve_captcha,
    _try_guest_bypass,
    _try_resume_upload_bypass,
    _wait_and_dismiss_cookies,
)
from jobapply.profile import (
    _STATE_NAMES,
    ApplicantProfile,
    JobSearchParams,
    _format_previous_employers,
    _profile_summary,
)
from jobapply.queue import (
    _DEEP_APPLY_ELIGIBLE_CATEGORIES,
    _deep_apply_eligible,
    _escalate_to_q3,
    _generate_deep_apply_prompt,
    _load_deep_apply_queue,
    _mark_deep_apply_done,
    _queue_for_deep_apply,
    _save_deep_apply_queue,
)
from jobapply.safety import (
    _ABORT_FIELD_PATTERNS,
    _INJECTION_PATTERNS,
    ApplicationAbortError,
    _check_field_label,
    _looks_like_injection,
    _sanitize_description,
)
from jobapply.search import (
    _BIOTECH_WORKDAY_SITES,
    _extract_results_count,
    _fetch_description,
    _parse_job_cards,
    _workday_job_detail,
    _workday_search,
    market_snapshot,
    search_biotech,
    search_hn_whos_hiring,
    search_linkedin,
    search_remoteok,
)
from jobapply.stats import (
    _ATS_PATTERNS,
    _categorize_failure,
    _compute_cost_usd,
    _detect_ats_platform,
)
from jobapply.workflow import auto_apply_workflow

# Facade re-exports: external consumers (ats_handlers/, assisted_apply_mcp.py,
# dashboard.py, tests/) import these names from job_search_apply. Listing them
# in __all__ marks them as intentionally exported for vulture and readers.
__all__ = [
    "ApplicantProfile",
    "ApplicationAbortError",
    "JobSearchParams",
    "ATS_ACCOUNTS_FILE",
    "CDP_URL",
    "COVER_LETTER_DIR",
    "CREDENTIALS_FILE",
    "DATA_DIR",
    "DEBUG_DIR",
    "DEEP_APPLY_QUEUE_FILE",
    "LOG_FILE",
    "PROFILE_SYNC_INTERVAL_DAYS",
    "SEARCH_LOG_FILE",
    "SESSION_FILE",
    "_ABORT_FIELD_PATTERNS",
    "_AI_AVAILABLE",
    "_ATS_PATTERNS",
    "_BIOTECH_WORKDAY_SITES",
    "_DEEP_APPLY_ELIGIBLE_CATEGORIES",
    "_FORM_FILL_SYSTEM",
    "_FORM_FILL_TEXTAREA_SYSTEM",
    "_GUEST_SELECTORS",
    "_INJECTION_PATTERNS",
    "_MAX_EXTERNAL_STEPS",
    "_PAGE_CLASSIFIER_SYSTEM",
    "_RESUME_UPLOAD_BYPASS_SELECTORS",
    "_STATE_NAMES",
    "_STEALTH",
    "_USER_AGENTS",
    "_2captcha_solve",
    "_ai_answer_question",
    "_ai_draft_hiring_message",
    "_ai_find_navigation_button",
    "_answer_external_screening_questions",
    "_answer_radio_buttons",
    "_answer_screening_questions",
    "_answer_select_dropdowns",
    "_answer_textareas",
    "_apply_synced_profile",
    "_attempt_account_creation",
    "_attempt_ats_login",
    "_basic_cover_letter",
    "_basic_notes",
    "_best_option_match",
    "_build_form_prompt",
    "_capsolver_solve",
    "_categorize_failure",
    "_check_field_label",
    "_check_mandatory_checkboxes",
    "_clamp_to_maxlength",
    "_classify_page",
    "_compute_cost_usd",
    "_contact_value_for_label",
    "_deep_apply_eligible",
    "_detect_ats_platform",
    "_detect_captcha",
    "_detect_login_page",
    "_detect_success_or_confirmation",
    "_determine_radio_answer",
    "_dismiss_all_typeaheads",
    "_dismiss_linkedin_overlays",
    "_dismiss_save_dialog",
    "_dismiss_typeahead",
    "_dump_form_debug",
    "_ensure_cover_letter_docx",
    "_ensure_logged_in",
    "_escalate_to_q3",
    "_extract_code_from_email_body",
    "_extract_hiring_manager",
    "_extract_page_snapshot",
    "_extract_results_count",
    "_fetch_description",
    "_fetch_verification_code_from_gmail",
    "_fill_custom_dropdown",
    "_fill_empty_required_fields",
    "_fill_input_field",
    "_fill_registration_form",
    "_find_file_upload_inputs",
    "_find_navigation_button",
    "_format_previous_employers",
    "_generate_ats_password",
    "_generate_deep_apply_prompt",
    "_get_ai_client",
    "_get_custom_dropdown_options",
    "_get_domain",
    "_get_field_label",
    "_get_form_container",
    "_get_modal_text",
    "_get_validation_errors",
    "_handle_file_uploads",
    "_handle_registration_verification",
    "_human_delay",
    "_inject_captcha_token",
    "_inject_session_cookies_if_needed",
    "_load_ats_accounts",
    "_load_credentials",
    "_load_deep_apply_queue",
    "_login_linkedin",
    "_looks_like_injection",
    "_mark_deep_apply_done",
    "_match_screening_answer",
    "_maybe_sync_profile",
    "_message_hiring_manager_after_apply",
    "_navigate_external_form",
    "_navigate_form",
    "_parse_job_cards",
    "_playwright_context",
    "_profile_summary",
    "_queue_for_deep_apply",
    "_resolve_login_wall",
    "_resolve_proxy",
    "_run_setup",
    "_safe_click",
    "_sanitize_description",
    "_save_ats_account",
    "_save_cover_letter_docx",
    "_save_credentials",
    "_save_deep_apply_queue",
    "_save_session",
    "_send_hiring_manager_message",
    "_solve_captcha",
    "_stealth_playwright",
    "_sync_linkedin_profile",
    "_try_guest_bypass",
    "_try_resume_upload_bypass",
    "_wait_and_dismiss_cookies",
    "_workday_job_detail",
    "_workday_search",
    "ai_build_notes",
    "ai_generate_cover_letter",
    "ai_score_job",
    "already_applied",
    "auto_apply_workflow",
    "load_log",
    "main",
    "market_snapshot",
    "save_log",
    "save_search_log",
    "score_job",
    "search_biotech",
    "search_hn_whos_hiring",
    "search_linkedin",
    "search_remoteok",
    "submit_easy_apply",
    "submit_external_apply",
]

logging.basicConfig(level=logging.INFO, format="%(message)s")

if __name__ == "__main__":
    main()
